# Generated by Django 5.1 on 2024-08-19 11:35

import django.db.models.deletion
import ongs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ong_name', models.CharField(max_length=40)),
                ('custom_url', models.CharField(default=models.CharField(max_length=40), max_length=20)),
                ('ong_address', models.CharField(max_length=200, validators=[ongs.models.validate_address])),
                ('ong_cnpj', models.CharField(blank=True, validators=[ongs.models.validate_cnpj])),
                ('ong_phone_number', models.IntegerField()),
                ('ong_email', models.CharField(validators=[ongs.models.email_validator])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('pet_age', models.IntegerField()),
                ('pet_vaccines', models.CharField(max_length=400)),
                ('pet_size', models.CharField(max_length=1)),
                ('is_pet_neutered', models.BooleanField()),
                ('is_pet_available', models.BooleanField(default=True)),
                ('pet_photos', models.ImageField(upload_to='images/')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ongs.ong')),
            ],
        ),
    ]
