# Generated by Django 5.0.3 on 2024-04-01 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ong_name', models.CharField(max_length=200)),
                ('ong_address', models.CharField(max_length=400)),
                ('ong_cnpj', models.IntegerField()),
                ('ong_phone_number', models.IntegerField()),
                ('ong_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('pet_age', models.IntegerField()),
                ('pet_vaccines', models.CharField(max_length=400)),
                ('pet_size', models.CharField(max_length=1)),
                ('is_pet_neutered', models.BooleanField()),
                ('is_pet_available', models.BooleanField(default=True)),
                ('pet_photos', models.ImageField(upload_to='images/')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ongs.ong')),
            ],
        ),
    ]
