# Generated by Django 5.1 on 2024-08-20 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0002_alter_ong_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='custom_url',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=20),
        ),
        migrations.AlterField(
            model_name='ong',
            name='ong_email',
            field=models.CharField(validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='ong',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
