# Generated by Django 5.1 on 2024-08-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0004_alter_ong_custom_url_alter_ong_ong_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ong',
            options={'permissions': [('pet_creation', 'can create pets')]},
        ),
    ]
