# Generated by Django 5.1 on 2024-09-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0006_customeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeruser',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
