# Generated by Django 5.0.7 on 2024-09-04 23:14

import ongs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0013_alter_pet_ong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='ong_cnpj',
            field=models.CharField(blank=True, unique=True, validators=[ongs.models.validate_cnpj]),
        ),
        migrations.AlterField(
            model_name='ong',
            name='ong_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
