# Generated by Django 5.1 on 2024-09-09 01:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0014_alter_ong_ong_cnpj_alter_ong_ong_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='custom_url',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ongs.ong')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ongs.customeruser')),
            ],
        ),
    ]
