# Generated by Django 5.1 on 2024-09-09 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0015_alter_ong_custom_url_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ongs.ong'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ongs.customeruser'),
        ),
    ]
