# Generated by Django 5.1 on 2024-09-10 02:48

import ongs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0016_alter_rating_ong_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=models.CharField(default="Não informado.", max_length=200, validators=[ongs.models.validate_address], null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ong',
            name='ong_name',
            field=models.CharField(max_length=40, unique=True, validators=[ongs.models.validate_name]),
        ),
    ]
